import {
  ArrowLeft, ArrowRight, ArrowUp,Award, ArrowRightSquare, Activity, Anvil, ArrowRightCircle, 
  BarChart3, BrickWall, Bell, Badge, BookOpen, Building2,
  CheckCircle, CheckSquare, Clock, Check, ChevronDown, ChevronUp, ChevronRight, CheckCircle2, Circle, Calendar, ChevronLeft, Settings,
  DollarSign, 
  Eye, Edit3, ExternalLink,
  FormInput, Folder, FolderPlus,
  Gauge, GripVertical, Users, GalleryVerticalEnd, GraduationCap,
  Home, Hand, HelpCircle, Hammer, Heart,
  Info, ImagePlus, Unlock,
  LogIn, LogOut, ListPlus, Layers,
  Moon, Mail, Minus, MinusSquare, Menu,
  Plus, PlusSquare, PlayCircle, Play, Pipette, Phone, PlusCircle, 
  Rocket, 
  SquareStack, Square, SquareCheck, Send, Star, Sun, ShieldQuestion, Share, Sparkles, Save,
  User, UserPlus, UserPlus2,
  ThumbsUp, Trash2,
  Trophy,
  Wand2, Watch,
  X, XCircle,
  Target,
  UserCircle,
  Zap, ZapOff,
  TrendingUp,
  FileText,
  RefreshCw,
} from '@tamagui/lucide-icons'
import React from 'react'

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
export function IconComp(props: any) {
  // icon key value pairs
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const icons: { [key: string]: any } = {
    about: Info,
    activity: Activity,
    add: Plus,
    add_image: ImagePlus,
    add_user: UserPlus,
    add_users: UserPlus2,
    admin: UserCircle,
    ai: Sparkles,
    arrow_left: ArrowLeft,
    arrow_right: ArrowRight,
    arrow_right_square: ArrowRightSquare,
    arrow_right_circle: ArrowRightCircle,
    arrow_up: ArrowUp,
    award: Award,
    anvil: Anvil,
    badge: Badge,
    bar_chart: BarChart3,
    book_open: BookOpen,
    building: Building2,
    score: BarChart3,
    bell: Bell,
    brick_wall: BrickWall,
    calendar: Calendar,
    check: Check,
    check_square: CheckSquare,
    check_circle: CheckCircle,  //play
    check_circle_2: CheckCircle2,
    circle: Circle,
    clock: Clock,                //play
    close: X,
    chevron_down: ChevronDown,
    chevron_up: ChevronUp,
    chevron_left: ChevronLeft,
    chevron_right: ChevronRight,
    cog: Settings,
    create: PlusSquare,         // home 
    deck: Layers,
    delete: Trash2,
    edit: Edit3,
    eye: Eye,
    gallery: GalleryVerticalEnd,
    feed: GalleryVerticalEnd,
    file_text: FileText,
    folder: Folder,
    folder_plus: FolderPlus,
    form: FormInput,
    free: User,
    gauge: Gauge,
    heart: Heart,
    hide: MinusSquare,
    home: Home,                 // profile
    help: HelpCircle,
    info: Info,
    layers: Layers,
    link: ExternalLink,
    list_plus: ListPlus,
    lock_open: Unlock,
    log_in: LogIn,               //profile
    log_out: LogOut,
    mail: Mail,
    menu: Menu,
    minus: Minus,
    moon: Moon,
    novice: Hammer,
    paid: DollarSign,
    phone: Phone,
    pipe: Pipette,
    play: Play,                 
    play_circle: PlayCircle,    //play
    plus: Plus,       
    plus_circle: PlusCircle,          
    profile: User,
    progress: BarChart3,
    private: ZapOff,
    public: Zap,
    question_circle: HelpCircle,
    question_shield: ShieldQuestion,
    rocket: Rocket,
    refresh_cw: RefreshCw, 
    remove: Minus,
    save: Save,
    send: Send,
    settings: Settings,
    share: Share,
    square: Square,
    square_check: SquareCheck,
    stack: SquareStack,
    star: Star,
    student: GraduationCap,
    subscription: DollarSign,
    sun: Sun,
    target: Target,
    team: Users,
    thumbnails: GripVertical,
    thumbs_up: ThumbsUp,
    trending_up: TrendingUp,
    trophy: Trophy,
    unhide: PlusSquare,
    unlock: Unlock,
    user: User,
    users: Users,
    waitlist: Hand,
    wand: Wand2,
    watch: Watch,
    x_circle: XCircle,
    zap: Zap
  }

  if (!icons[props.name]) {
    return null
  }

  // Filter out non-DOM props before passing to the icon
  const { name, ...validProps } = props
  return React.createElement(icons[name], validProps, null)
}
